window.PE_PRODUCTS = [
  ["neem", "Neem", 45, "50gm", "Skin Care", "#446b45", "Face pack and scalp care", "Helps with purifying face packs and scalp-care routines.", "Mix with water, curd, or rose water. Apply briefly and rinse.", "Tulsi, Mulethi, Multani Mitti", "Face Pack, Dandruff", "assets/products/neem-powder.png"],
  ["tulsi", "Tulsi", 60, "50gm", "Skin Care", "#568c55", "Herbal face care", "Useful in herbal skin and scalp routines.", "Mix into a smooth paste and apply after patch testing.", "Neem, Mulethi", "Face Pack, Dandruff", "assets/products/tulsi-powder.png"],
  ["amla", "Amla", 45, "50gm", "Hair Care", "#8b9d3f", "Hair care routines", "Traditional ingredient for hair strength and shine routines.", "Use in a hair pack or blend with Reetha and Shikakai.", "Reetha, Shikakai, Bhringraj", "Hair Fall", "assets/products/amla-powder.png"],
  ["reetha", "Reetha", 45, "50gm", "Hair Care", "#8a6042", "Natural cleanser", "Traditional natural cleanser for hair wash mixes.", "Blend with Shikakai and Amla for a wash powder.", "Amla, Shikakai", "Hair Wash", "assets/products/reetha-powder.png"],
  ["shikakai", "Shikakai", 45, "50gm", "Hair Care", "#9a6b3e", "Traditional hair wash", "Classic hair wash ingredient for gentle cleansing.", "Mix with Reetha and Amla, then rinse thoroughly.", "Amla, Reetha", "Hair Wash", "assets/products/shikakai-powder.png"],
  ["bhrami", "Bhrami", 80, "50gm", "Hair Care", "#527b4a", "Hair and scalp care", "Popular in scalp-care and hair pack routines.", "Add to hair masks with water or aloe gel.", "Bhringraj, Amla", "Hair Fall", "assets/products/bhrami-powder.png"],
  ["bhrangraj", "Bhringraj", 60, "50gm", "Hair Care", "#315b3b", "Hair care ingredient", "Traditional hair-care powder for strengthening routines.", "Use in a weekly hair pack with Amla or Hibiscus.", "Amla, Hibiscus", "Hair Fall", "assets/products/bhringraj-powder.png"],
  ["methi", "Methi", 35, "50gm", "Hair Care", "#c69a3d", "Hair mask routines", "Often used in softening hair masks.", "Soak or mix as powder into a paste and rinse well.", "Amla, Hibiscus", "Dandruff, Hair Fall", "assets/products/methi-powder.png"],
  ["moringa", "Moringa", 80, "50gm", "Herbal", "#5f8a40", "Herbal powder", "Nutrient-rich herbal powder for natural routines.", "Use in small amounts in face or hair packs.", "Tulsi, Neem", "Glow", "assets/products/moringa-powder.png"],
  ["hibiscus-flower", "Hibiscus Flower Powder", 120, "50gm", "Floral", "#b6415b", "Hair and floral care", "Floral powder used in hair masks and softening routines.", "Mix with Amla or Bhringraj for hair packs.", "Amla, Bhringraj", "Hair Fall, Floral", "assets/products/hibiscus-flower-powder.png"],
  ["hibiscus-leaves", "Hibiscus Dried Leaves", 100, "50gm", "Floral", "#7d3d50", "Dried botanical", "Dried botanical for herbal preparations.", "Crush or steep as needed for the routine.", "Hibiscus Flower Powder", "Floral", "assets/products/hibiscus-dried-leaves.png"],
  ["rose-leaves", "Dry Rose Leaves", 80, "50gm", "Floral", "#c36a78", "Floral care", "Floral ingredient for refreshing skin-care routines.", "Use crushed petals in face packs or bath blends.", "Gulab Jal, Mulethi", "Glow, Floral", "assets/products/dry-rose-leaves.png"],
  ["orange-peel", "Orange Peel Powder", 40, "50gm", "Skin Care", "#dc8435", "Face pack ingredient", "Brightening-style ingredient for face packs.", "Mix with rose water or curd, then rinse before fully dry.", "Multani Mitti, Gulab Jal", "Glow, Face Pack", "assets/products/orange-peel-powder.png"],
  ["multani-mitti", "Multani Mitti Powder", 60, "50gm", "Skin Care", "#b99562", "Clay face pack", "Classic clay base for face packs.", "Mix with rose water for a smooth paste.", "Gulab Jal, Neem", "Face Pack, Glow", "assets/products/multani-mitti-powder.png"],
  ["mulethi", "Mulethi Powder", 80, "50gm", "Skin Care", "#d0a856", "Skin care routines", "Popular powder for glow-focused face packs.", "Use with rose water or other face pack bases.", "Tulsi, Neem, Rose", "Glow, Face Pack", "assets/products/mulethi-powder.png"],
  ["rosemary", "Rosemary Leaves", 150, "50gm", "Herbal", "#456e67", "Herbal care", "Premium herbal ingredient for hair-care routines.", "Use in hair masks or herbal preparations.", "Bhringraj, Amla", "Hair Fall", "assets/products/rosemary-leaves.png"],
  ["alsi", "Alsi", 35, "50gm", "Herbal", "#b1704a", "Natural powder", "Natural ingredient used in softening routines.", "Use carefully in blends for texture and slip.", "Methi, Amla", "Hair Fall", "assets/products/alsi-powder.png"],
  ["beetroot", "Beetroot Powder", 70, "50gm", "Skin Care", "#9b2345", "Natural color and care", "Adds natural color and freshness to skin-care blends.", "Use a small amount in face packs.", "Rose, Mulethi", "Glow", "assets/products/beetroot-powder.png"],
  ["gulab-jal", "Gulab Jal", 50, "50ml", "Floral", "#d78a98", "Rose water", "Cooling floral water for face packs.", "Use as the liquid base for powders.", "Multani Mitti, Rose Leaves", "Glow, Floral", "assets/products/gulab-jal.png"],
  ["cucumber", "Cucumber Powder", 70, "50gm", "Skin Care", "#7aa66a", "Cooling face care", "Cooling-style powder for refreshing face packs.", "Mix with rose water or plain water.", "Multani Mitti, Mulethi", "Face Pack, Glow", "assets/products/cucumber-powder.png"]
].map(([id, name, price, unit, category, color, note, benefits, usage, pairs, concerns, image]) => ({
  id, name, price, unit, category, color, note, benefits, usage, pairs, concerns, image
}));

window.PE_COMBOS = [
  { id: "hair-strength-blend", name: "Amla + Reetha + Shikakai + Bhringraj + Hibiscus", label: "Hair Strength Blend", price: 80, unit: "50gm", category: "Combo", color: "#6b7740", note: "Traditional mix for hair wash and care routines.", benefits: "Ready blend for a simple hair-care starting point.", usage: "Mix with water, apply to hair and scalp, then rinse thoroughly.", pairs: "Gulab Jal or plain water", concerns: "Hair Fall", image: "assets/products/hair-strength-blend.png" },
  { id: "clear-skin-blend", name: "Tulsi + Neem + Mulethi", label: "Clear Skin Blend", price: 70, unit: "50gm", category: "Combo", color: "#537d55", note: "Herbal blend for simple face pack routines.", benefits: "Ready blend for skin-care routines.", usage: "Mix with rose water, patch test, apply briefly, and rinse.", pairs: "Gulab Jal, Multani Mitti", concerns: "Face Pack, Glow", image: "assets/products/clear-skin-blend.png" },
  { id: "dried-botanicals", name: "Dried Leaves", label: "Dried Botanicals", price: 90, unit: "50gm", category: "Combo", color: "#ad5363", note: "Natural dried leaves for herbal preparations.", benefits: "Useful for floral and herbal preparations.", usage: "Crush, steep, or blend as needed.", pairs: "Dry Rose Leaves, Hibiscus", concerns: "Floral", image: "assets/products/dried-leaves.png" }
];
